# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

language: go

services:
  - redis-server

dist: bionic

os:
- linux
- osx

go:
- tip
- 1.14.x
- 1.13.x
- 1.12.x
- 1.11.x
# - 1.10.x

script: go test ${gobuild_args} -v ./...

before_install:
- go get -t -v ./...

jobs:
  allow_failures:
  - go: tip
  
  fast_finish: true
  
  include:
  - name: standard-platform
    stage: test
    script:
    #  build test for supported platforms
    - GOOS=linux go build ./...
    - GOOS=darwin go build ./...
    - GOOS=freebsd go build ./...
    - GOOS=windows go build ./...
    - GOARCH=386 go build ./...
    - go get golang.org/x/tools/cmd/cover
    - go get github.com/mattn/goveralls
    # run tests on a standard platform
    - INTEGRATION_TEST=true go test -v -covermode=count -coverprofile=coverage.out ./...
    # collect coverage
    - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-pro -repotoken $COVERALLS_TOKEN
    # run tests with the race detector as well
    - INTEGRATION_TEST=true go test -race -v ./...

env:
  global:
    - secure: "jksqPzzIqEA1Y74v0u/X9uAtDllz3pSFy9HAWP1qaMxjv7du7m6NuHDKma6pZRLAZ9donyD2xa1dQUg7j7OmT+FViOtAdOh6f0JkR03UjPVsM54aFhtsmg/ncCno4hZWAwLh/UpcLsuTjKU6bK1Xhyhal/OcIThzCEX0tXz/QMGUt3XQUq7vm+ziDw4yv5jhhKr4TkMnsZu/jMw4e39vFqD+EjCMqqO+JrLzxl7wW8UUZVwu/RABjYZYWiHSoMMzhv8hvHkKSYXKOb/t0F2CcPyZwsCdLs4bu4yT2KOA8GYJAj/KQb+lNtLkLUI1S5ylIKMtXwfGH9M9zt4drQjlNeUhLfeEEYergVqPyHj8yKIttpRPy8UbR31CyV3i6DYhzUa9wO29fMUBvJo+Dhw8KBK6kxKoJyTi7l2F+IOkueURl6bS+d43R8r98IHlHrrJzFZr/4X0if3lTfPXWZBVsGygVpz5vwiPStSo8JUokUka4hJIJCLX0psZhe1EJdo/ibMOZjQSnBIgaPeIHnchL/MgW/Vp1/lnf1K+BBt+t8oxhTdPxvt1kNI3zPsHu6MedsOiFFZTY2KcfnDoyEoQ3Qt+E4zrBrlC/GNzwUI+z/MDXkG4QR4s1ultxHbGfF/9Z81cKtRyPwBwOx/n8IXR2La3CZSiedyZRAdg/Zg4BzU="
  jobs:
    - GO111MODULE=on
